port: 2802

httpPort: 8080

scenarios:
 - bridge

architectServers:
 - hostname: localhost
   port: 10000
 - hostname: localhost
   port: 10001

database:
  url: "jdbc:mysql://localhost:3306/"
  username: "root"
  
