port: 2802

httpPort: 8080

scenarios:
 - house

architectServers:
 - hostname: localhost
   port: 10000
# you can add more servers:
# - hostname: localhost
#   port: 10001

database:
  url: "jdbc:mysql://localhost:3306/"
  username: "minecraft"
